create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  bandeira text not null,
  final text not null,
  vencimento_dia int not null check (vencimento_dia between 1 and 28),
  fechamento_dia int not null check (fechamento_dia between 1 and 28),
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  descricao text not null,
  valor numeric not null,
  tipo text not null,
  categoria text not null,
  data date not null,
  status text not null default 'pago',
  metodo_pagamento text not null default 'debito',
  card_id bigint references public.cards(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  alvo numeric not null,
  atual numeric not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists transactions_user_id_idx on public.transactions(user_id);
create index if not exists goals_user_id_idx on public.goals(user_id);
create index if not exists cards_user_id_idx on public.cards(user_id);

alter table public.cards enable row level security;
alter table public.transactions enable row level security;
alter table public.goals enable row level security;

create policy "Cards are private"
on public.cards
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Transactions are private"
on public.transactions
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Goals are private"
on public.goals
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
