create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  bandeira text not null,
  final text not null,
  vencimento_dia int not null check (vencimento_dia between 1 and 28),
  fechamento_dia int not null check (fechamento_dia between 1 and 28),
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  descricao text not null,
  valor numeric not null,
  tipo text not null,
  categoria text not null,
  data date not null,
  status text not null default 'pago',
  metodo_pagamento text not null default 'debito',
  card_id bigint references public.cards(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  alvo numeric not null,
  atual numeric not null default 0,
  contrib_percent numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.investments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  aporte_inicial numeric not null,
  valor_atual numeric not null,
  data_inicio date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.investment_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  investment_id bigint not null references public.investments(id) on delete cascade,
  data date not null,
  valor numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.recurring_rules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  descricao text not null,
  valor numeric not null,
  tipo text not null,
  categoria text not null,
  status text not null default 'pago',
  metodo_pagamento text not null default 'debito',
  card_id bigint references public.cards(id) on delete set null,
  day_of_month int not null check (day_of_month between 1 and 28),
  start_date date not null,
  end_date date,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.recurring_instances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  rule_id bigint not null references public.recurring_rules(id) on delete cascade,
  year int not null,
  month int not null,
  transaction_id bigint references public.transactions(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (rule_id, year, month)
);

create table if not exists public.card_invoices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  card_id bigint not null references public.cards(id) on delete cascade,
  cycle_year int not null,
  cycle_month int not null,
  status text not null default 'aberta',
  fechamento_date date not null,
  vencimento_date date not null,
  total numeric not null default 0,
  created_at timestamptz not null default now(),
  unique (card_id, cycle_year, cycle_month)
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  tipo text not null,
  cor text,
  created_at timestamptz not null default now()
);

create table if not exists public.goal_contributions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  goal_id bigint not null references public.goals(id) on delete cascade,
  month int not null,
  year int not null,
  valor numeric not null,
  created_at timestamptz not null default now(),
  unique (goal_id, month, year)
);

create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category_key text not null,
  monthly_limit numeric not null,
  alert_threshold numeric not null default 0.8,
  created_at timestamptz not null default now(),
  unique (user_id, category_key)
);

create table if not exists public.notification_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  frequency text not null default 'weekly',
  last_sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.insights_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  month int not null,
  year int not null,
  insights jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists transactions_user_id_idx on public.transactions(user_id);
create index if not exists goals_user_id_idx on public.goals(user_id);
create index if not exists cards_user_id_idx on public.cards(user_id);
create index if not exists investments_user_id_idx on public.investments(user_id);
create index if not exists investment_history_user_id_idx on public.investment_history(user_id);
create index if not exists investment_history_investment_id_idx on public.investment_history(investment_id);
create index if not exists recurring_rules_user_id_idx on public.recurring_rules(user_id);
create index if not exists recurring_instances_user_id_idx on public.recurring_instances(user_id);
create index if not exists card_invoices_user_id_idx on public.card_invoices(user_id);
create index if not exists categories_user_id_idx on public.categories(user_id);
create index if not exists goal_contributions_user_id_idx on public.goal_contributions(user_id);
create index if not exists budgets_user_id_idx on public.budgets(user_id);
create index if not exists notification_settings_user_id_idx on public.notification_settings(user_id);
create index if not exists insights_history_user_id_idx on public.insights_history(user_id);

alter table public.cards enable row level security;
alter table public.transactions enable row level security;
alter table public.goals enable row level security;
alter table public.investments enable row level security;
alter table public.investment_history enable row level security;
alter table public.recurring_rules enable row level security;
alter table public.recurring_instances enable row level security;
alter table public.card_invoices enable row level security;
alter table public.categories enable row level security;
alter table public.goal_contributions enable row level security;
alter table public.budgets enable row level security;
alter table public.notification_settings enable row level security;
alter table public.insights_history enable row level security;

drop policy if exists "Cards are private" on public.cards;
drop policy if exists "Transactions are private" on public.transactions;
drop policy if exists "Goals are private" on public.goals;
drop policy if exists "Investments are private" on public.investments;
drop policy if exists "Investment history is private" on public.investment_history;
drop policy if exists "Recurring rules are private" on public.recurring_rules;
drop policy if exists "Recurring instances are private" on public.recurring_instances;
drop policy if exists "Card invoices are private" on public.card_invoices;
drop policy if exists "Categories are private" on public.categories;
drop policy if exists "Goal contributions are private" on public.goal_contributions;
drop policy if exists "Budgets are private" on public.budgets;
drop policy if exists "Notification settings are private" on public.notification_settings;
drop policy if exists "Insights history is private" on public.insights_history;

create policy "Cards are private"
on public.cards
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Transactions are private"
on public.transactions
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Goals are private"
on public.goals
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Investments are private"
on public.investments
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Investment history is private"
on public.investment_history
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Recurring rules are private"
on public.recurring_rules
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Recurring instances are private"
on public.recurring_instances
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Card invoices are private"
on public.card_invoices
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Categories are private"
on public.categories
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Goal contributions are private"
on public.goal_contributions
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Budgets are private"
on public.budgets
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Notification settings are private"
on public.notification_settings
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Insights history is private"
on public.insights_history
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
